[build]
command = "npm run build"
publish = "dist"
# functions = "./src/functions"

[context.production]
environment = {NODE_VERSION = "10.15.3", NODE_ENV = "production"}

[dev]
NODE_ENV = "development"
command = "npm run start"
framework = "#custom"
port = 3000
publish = "dist"
targetPort = 8181
# functionsPort = 34567

[[redirects]]
from = "/post/*"
to = "/blog/:splat"
